site_name: EagleRepair
copyright: Copyright &copy; 2022 Martin Odermatt, Diego Marcilio, Carlo A. Furia
repo_url: https://github.com/marodev/EagleRepair
site_url: https://marodev.github.io/EagleRepair
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marodev/EagleRepair
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/marodev
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
    
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  features:
    - navigation.top
  icon:
    repo: fontawesome/brands/github
    
  nav:
    - EagleRepair: index.md
    - rules.md
    - contributing.md
